e2nIEE/pandapower

pandapower/results.py
pandapower/results_bus.py

Comments welcome.
For me the test `test_IEEE_case_9_with_bad_data` is failing, but it also fails on `develop`.

Include Lagrange multipliers in results from OPF

---

doc/shortcircuit/ip.rst

according to IEC-60909 (page 101), the index of kappa looks like _"-3R/X"_

change to peak factor calculation

---

setup.py

Corrects the following errors:
```
error in pandapower setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
```
```
Expected ',' or end-of-list in pandas>=0.17.0<0.20 at <0.20
```

Fix pandas requirement specification

---

pandapower/shortcircuit/results.py

There seem to be a couple of keys missing from `_get_trafo3w_results`.

Added keys to trafo3w results function

---

pandapower/build_branch.py
pandapower/powerflow.py

I changed iterrows to itertuples for creating three-winding transformers, because it is significantly faster. This speeds up the function from about 0.8 seconds to 0.2 seconds for 1000 three winding transformers. 
The best way would still be no iteration at all, but that would be more complex. 
I got rid of the iteration in the bus creation for extended wards and three-winding transformers, this has an even greater impact on speed with init='results', something like from 8 seconds down to less than 1 second.

Speed improvements

---

pandapower/auxiliary.py
pandapower/powerflow.py
pandapower/test/loadflow/test_scenarios.py

This prevents an unsupplied ad_bus which is set in_service. Otherwise the powerflow cannot converge. I think with this #118 can be closed.

Check if all trafo buses are in_service and set ad_bus accordingly

---

pandapower/plotting/plotly/traces.py

Affects #140 
Currently, a custom marker for buses in plotly is only accepted if no cmap argument is given.

accept custom marker symbols for plotly create_bus_trace even when colormap is given

---

.travis.yml
pandapower/io_utils.py
pandapower/test/api/test_file_io.py
setup.py

With the new to_json method, it is possible to encode pandapower nets to json using the builtin to_json methods of pandas. I have been working on not only having a function that allows to convert a single pandapower net, but to register the pandapowerNet object with the JSON handler, so that it can convert any data structure that contains a pandapower net like this:
```
d = {"a": net, "b": [1,2,3]}
json_string = json.dumps(d, cls=PPJSONEncoder)
d = json.loads(json_string, cls=PPJSONDecoder)
````
In addition, I have registered sets, tuples and frozensets with the PPJSONEncoder/PPJSONDecoder so that they can be safely encoded and decoded. I have implemented a [workaround](https://github.com/lthurner/pandapower/blob/1c2df09a5a533fb8e8f9463e6dffaf02f5d4d5e3/pandapower/io_utils.py#L191-L194) …

JSON encoding / decoding

---

pandapower/auxiliary.py
pandapower/shortcircuit/calc_sc.py

Hi,
The `consider_sgens` option shown in the [latest documentation](https://pandapower.readthedocs.io/en/latest/shortcircuit/run.html) has no actual impact on the calculation output. It was simply set to `False` in the `_add_sc_options` method in `calc_sc.py`.
Considering this and the fact that I see no reason to include such an option, I would recommend removing it, hence the current PR. I assume it's an old option that was used during development.
I also added the option `branch_results`. I know it's not 100% ready, but it appears in the doc with no description so it should be described somehow.
I'm not very familiar with this but it *looks* like the doc is autogenerated from the docstring and [this file](https://github.com/e2nIEE/pandapower/blob/master/doc/shortcircuit/run.rst), which …

Removed unused option (no impact on calculation)

---

pandapower/estimation/state_estimation.py
pandapower/estimation/wls_ppc_conversions.py
pandapower/test/estimation/test_wls_estimation.py

Fix #253 
- in case of bb switches, with the option fuse_all_bb_switch disabled, the module will find such auto fused buses with elements on them, and create auxiliary buses to substitute the bus in the original topology with bb switches, the original bus will then connect to the auxiliary bus with a short piece of line, thus avoiding
auto fusing, this process will be done in the estimation function before the pd2ppc conversion and and cleaned at the end of the function ofr the unnecessary information
- Added test case

Fix #253 Avoid auto fusing of buses with elements and bb switches in state estimation

---

pandapower/plotting/generic_geodata.py

The stable version of networkx.MultiGraph uses `edges` to return the iterator, not `edges_iter`. See here: https://networkx.github.io/documentation/stable/reference/classes/multigraph.html
I would like to test this completely but I'm having issues with the compilation of graphviz, sorry. I recommend someone tests this before merging (not that it has any chance of breaking anything, but other changes might be required).
Edit: Added "WiP" for this reason (couldn't test).
Michel

WiP: networkx MultiGraph method edges_iter -> edges

---

pandapower/io_utils.py

I found that when saving an old network with the new json io and reloading it, there are some discrepancies, as some values are found not to precisely match, i.e. after saving and loading a value that was 0.95 could now be 0.9500000001. In order avoid this, a keyword was added to the pp_hook (namely precise_float for the function to load DataFrames from json). It should slow down the process slightly, but ensures that the values always remain the same after loading. Maybe in the long run this should be outsourced to a kwarg, but for now I think it is better to have a slower function (btw. for my network it was 755 ms vs. 725 ms) than unprecise values.

added precise_float keyword to pp_hook for loading json networks

---

pandapower/create.py
pandapower/estimation/ppc_conversions.py
pandapower/test/estimation/test_wls_estimation.py
pandapower/toolbox.py

Bug fixed in create measurement in case of user defined column existed in measurement table
Bug fixed in trafo3w branch mapping in state estimation
Bug fixed in replace bb switch with small impedance
P, Q injection measurement on the same ppci bus (fused from same pp buses) will be added together if replace with impedance is not wanted and warning will be shown if such case happened, and also added test case, as mentioned in #277

Bug fixing in state estimation and support auto addition for p,q injection measurements duplication 

---

pandapower/create.py

Sometimes I had no need to use the standard types for lines and transformers, but instead had to add new ones.
So I propose a new optional argument to load standard element types into the pandapower network when create_empty_network() is called. This is a small change to enhance a bit this wonderful project.

Optional argument to load std_types on empty network

---

pandapower/pf/makeBdc.py

csr_matrix dimesions has to be specified explicitly.
Issue #288

fixed rundcpp with single bus network

---

pandapower/auxiliary.py
pandapower/build_bus.py
pandapower/test/loadflow/test_runpp.py

Alternative solution to the problem discusse in #262, this makes #263 obsolete.

move check for existing results in case of init=results to options #262

---

pandapower/auxiliary.py
pandapower/build_branch.py
pandapower/build_bus.py
pandapower/test/loadflow/result_test_network_generator.py
pandapower/test/loadflow/test_scenarios.py
pandapower/test/topology/test_create_graph.py
pandapower/topology/create_graph.py

Completely new implementation for create_nxgraph. Improvements compared to the previous version:
- much faster by using numpy instead of pandas ins many places
- uses the functions from build_branch to calculate branch impedances
- correctly considers trafo3w switches
- added tests for all relevant elements
See further discussion in #271.

Refactoring create_nxgraph

---

pandapower/plotting/generic_geodata.py

.ix is deprecated and leads to more or less undesired behaviour, as it has a fall-back to iloc, therefore some errors might be ignored silently. For this reason, I changed the respective calling function `build_igraph_from_pp` to use at instead of ix.
Hint: using `fb, tb = net.line.loc[lix, ["from_bus", "to_bus"]]` is more than 10 times slower than the version with at when iterating over the lines.
What might be even faster is not iterating, but putting `g.add_edges_from(zip(net.line.loc[~net.line.index.isin(nogolines), ["from_bus", "to_bus"]]))` or something of that kind.

changed deprecated ix to at in creating generic geodata

---

pandapower/plotting/plotly/pf_res_plotly.py
pandapower/plotting/plotly/traces.py

There are two changes I made in plotting.plotly
1.) As the position of the colorbar-title can't be set by the variable titleside anymore, I made some changes so that the title of the colorbar is now at the right position again.
2.) I thought it would make sense to be able to change the voltage and load colorbar limits as the relevant limits might not be 0.9 and 1.1 in case of voltage and 0 and 100 in case of loading in a heatmap. 
This, however, might cause collusions between the two colorbars. Therefore I also intoduced the variable colorbar_position. Maybe it is a bit of an overload and could be moved to **kwargs instead.
What do you think?

Changes in Plotly

---

pandapower/std_types.py

Added several 110 kV overhead line types:
- 48-AL1/8-ST1A 110.0
- 70-AL1/11-ST1A 110.0
- 94-AL1/15-ST1A 110.0
- 122-AL1/20-ST1A 110.0
- 490-AL1/64-ST1A 110.0
- 679-AL1/86-ST1A 110.0
And one more type for 220 and 380 kV power lines:
- 679-AL1/86-ST1A 220.0
- 679-AL1/86-ST1A 380.0

Added more std_types for overhead lines

---

doc/opf/formulation.rst
doc/opf/opf_flexibility.csv

- Introduce OPF as abbreviation
- Fixed spelling mistakes 
- Uniform headings (capitalization)
- "kilo" to "mega"

Fixed minor mistakes in OPF doc

---

pandapower/control/basic_controller.py
pandapower/control/util/auxiliary.py
pandapower/convert_format.py
pandapower/io_utils.py
pandapower/toolbox.py

After the implementation of new json IO, the dtypes are stored in the json file and are restored when loading the net. Therefore, the setting of dtypes in convert_format is no longer necessary, especially in the case when the user sets a different dtype of a column on purpose.
The functionality can still be used manually, with the function set_data_type_of_columns_to_default in pandapower.toolbox. The function overwrites the dtypes of all columns in element tables to match the dtypes in pandapower.create_empty_network.

Setting dtypes of columns in convert_format only for versions <1.6

---

pandapower/control/basic_controller.py
pandapower/control/util/auxiliary.py
pandapower/test/control/test_control.py

The former implementation of check_controller_frame had "astype" statements with no effect.
The new implementation sets the dtypes explicitly, and _preserve_dtypes is used when adding a new controller to the DataFrame.
Additional tests have been added to test_control.

Use _preserve_dtypes for net.controller table

---

pandapower/create.py
pandapower/test/api/test_create.py

For calculating the base Z value, sn_kva used to be divided by 1000 to convert it in sn_mva in the formula v^2/sn_mva.
After the transition to MW from kW, this is not necessary and produces incorrect per-unit values.
The division by 1000 is no longer necessary.

Bugfix in create_series_reactor_as_impedance

---

pandapower/toolbox.py

It should be possible to only give a lookup for some of the buses for which to change the indices and keep the indices for all other buses. This can be switched on with the partial flag. It would also make sense to always automatically check if all bus indices given in the lookup occur in the net and the values don't appear in the rest of the bus indices and then extend the lookup.

extended toolbox function reindex_buses for partial bus lookup

---

tutorials/time_series.ipynb
tutorials/time_series_advanced_output.ipynb

This PR simply removes the unneeded output_writer argument, avoiding the deprecation message,
since OutputWriter constructor takes a *net* argument and assigns itself.

run_timeseries deprecates output_writer keyword argument

---

pandapower/build_bus.py
pandapower/create.py
pandapower/pd2ppc_zero.py
pandapower/toolbox.py

Modfications to avoid deprecations mostly.
Does not handle:
- old format case files
- warnings from dependencies: I'm looking at you xlsx.py
- hard warnings about divide by zero and matrix singularity

Quiet down the warnings emitted by the unit tests.

---

pandapower/control/controller/const_control.py
pandapower/create.py
pandapower/test/control/test_const_control.py

Closing the issue #609 by disabling the option for write="all_index" in ConstControl
Closing #610 by first adding a row with .loc, and then setting geodata with .at.

Bugfix in ConstControl and create_line with geodata

---

pandapower/create.py

Hi.
This pull request refers to #638 
The following changes were made:
1. Functions **create_load**, **create_loads**, **create_sgen**, **create_storage**: if "controllable" arg is not NaN, create "controllable" column in the DataFrame and defaults the values of previous elements in it to False
2. Function **create_gen**: if "controllable" arg is not NaN, create "controllable" column in the DataFrame and defaults the values of the previous elements in it to True
3. Function _create_column_and_set_value: if *__variable__* is not NaN, create *__column__* in the DataFrame and defaults the values of the previous elements in it to *float(__default_val__)*
Thanks.

Small Bug corrections in create_* functions

---

pandapower/auxiliary.py
pandapower/test/api/test_auxiliary.py
pandapower/test/api/test_file_io.py

1) if net.bus_geodata or net.line_geodata are a GeoDataFrame, net.deepcopy() returned them as pd.DataFrame, because GeoDataFrame is a subclass of DataFrame, check "isinstance(v, pd.DataFrame)" was True.
2) after initializing a DataFrame with index and columns, the values in the DataFrame are np.nan. Casting with astype would lead to an error if np.nan could not safely be cast to a given type (e.g. int). This is fixed by using pandapower.auxiliary._preserve_dtypes
3) Added tests

Bugfix deepcopy

---

pandapower/plotting/plotly/traces.py

Modified handling of cmin and cmax in create_bus_trace() and create_line_trace() to avoid setting cmin (resp. cmax) to cmap_vals.min() (resp. cmap_vals.max()) when cmin == 0 (resp. cmax == 0).

Modified handling of cmin and cmax.

---

pandapower/auxiliary.py

IDEs can not easily autocomplete attributes of the pandapowerNet/ADict since attributes are modified dynamically. With this change IDEs that use ``__dir__`` to list attributes will be able to offer autocomplete at runtime. This works in pycharm in the debug console, for example. Doesn't help with static analysis of code, for that a stub file would probably be the way to go. 
Before:
After:

add __dir__ to assist IDEs finding attributes of network object

---

pandapower/io_utils.py

Problem: with some grids, the index of a dataframe can be interpreted as DateTime automatically. To prevent that, an option "convert_axes" in pd.read_json is set to False explicitly.

added convert_axes=False in json_io to prevent automatic date conversion

---

pandapower/plotting/collections.py

only using copy might cause information to get lost. For example it can happen, that patch information is not copied solely using copy.copy()

deepcopy collection

---

.gitignore

in order to integrate big data in our repo directly, I suggest to have a folder called 'data', where you can put big data without integrating it into the git repo. For that this folder needs to be in .gitignore.
For Uni Kassel/Fraunhofer employees: We could put all big data concerning pandapower in one owncloud/teams folder and synchronize it with this data folder (big test grids, in future files of the load profile generator...). By that we have one centralized location for all big files concering pandapower.

integrate big data 

---

pandapower/test/api/test_toolbox.py
pandapower/toolbox.py

I was working on a large network, and select_subnet would take around 10-20 seconds to execute. I figured out that the bottleneck was the list comprehension with iterrows for the switches. (see the diff)
With this PR, execution time for select_subnet(net, buses) is reduced to around 100ms from 10-20 seconds.
Issue: https://github.com/e2nIEE/pandapower/issues/769

Optimization: Remove iterrows from select_subnet() to improve performance for larger grids.

---

.travis.yml
setup.py

Changed pandas requirements in setup.py to reflect that pandapower doesn't work with pandas 1.
- pandas 1 causes short circuit tests to fail (looked like a pretty trivial fix though)
- pandas 1 has caused issues for other people #736 
- pandas 0 is specified in travis

pandas req <1.0.0

---

pandapower/convert_format.py
pandapower/file_io.py
pandapower/io_utils.py
pandapower/test/api/test_file_io.py
pandapower/test/test_files/controller_containing_NoneNan.json

There has been a problem with controllers containing NaNs or Nones in the column controller/object. It is not possible to perform the pp_hook on the columns controller/object containing either NaNs or NaNs. It will raise an error. However, as it might be possible, that there are grids containing both columns one with None entries (happend in pandapipes) it is not possible anymore to load those grids. In order to prevent this, I added an if-condition. 
As I thought it wouldn't make sense to do this in general, I just added it to the part handling the controllers. I didn't touch the pp_hook. 
I also added  a test!

Bugfix pp hook

---

pandapower/test/opf/test_costs_pwl.py

Fixes the error discussed in #884 using `np.isclose` instead of comparison `==`.
(also added an emptyline at end of file because github online editor apparently does this)

fixed assertion error with np.isclose

---

tutorials/opf_basic.ipynb

As reported in #733 and #748 since version 2.2.0 the basic OPF tutorial is not converging anymore. This was fixed by reducing the power tolerance `delta=1e-16` in `runopp()`.

Not converging OPF tutorial

---

pandapower/test/api/test_toolbox.py
pandapower/test/toolbox.py
pandapower/toolbox.py

Update bus IDs for net.asymmetric_load and net.asymmetric_sgen when merging nets.
I feel like this is a small piece of a larger refactor needed to support asymmetric elements in toolbox.py, so it's fine if you want to ignore this.

fix(toolbox): merge asymmetric elements

---

pandapower/test/api/test_toolbox.py
pandapower/toolbox.py

Fixed wrong consideration of trafo3w switches in pandapower toolbox.
Functions that were affected:
* drop_trafos
* set_isolated_areas_out_of_service
* get_connected_buses
* get_connected_switches
Also fixed the tests that did not catch the mistakes.

fixed bugs in pandapower toolbox related to the implementation of trafo3w

---

pandapower/io_utils.py

fixed a bug in the function io_utils:
removed the default "module" parameter from @from_serializable.register(class_name='function')

io_utils: bugfix for functions as attributes of classes

---

pandapower/io_utils.py

if an object attribute is a function that cannot be loaded, e.g. a lambda or if the function definition has been removed, raise a more clearly worded error for the user.

JSON I/O: Raise an explicit error if a function is not defined

---

pandapower/powerflow.py
pandapower/test/loadflow/test_runpp.py

Fixes #905.
Check if there are neither PQ buses nor PV buses and bypass the powerflow, and set the results from reference bus(es) instead.
Replaces the behavior for the case if there are no branches.
It also works for the case when there are no branches in the grid because there are no PQ buses in ppci if there are no branches (in this case, the PQ buses are disconnected/unsupplied and therefore not included in ppci['bus']).

Update powerflow.py - fix the behavior when there are only reference buses in the grid or there are no branches

---

.travis.yml

Python 3.5 fails with travisCI sometimes, and it is not clear why this happens.
GitHub Actions run through for python 3.5.

Update .travis.yml - remove python 3.5

---

pandapower/file_io.py
setup.py

newer versions of xlrd (used in pandas) dropped support for anything other than .xls, and using an older version of xlrd is not recommended for security reasons.

switch engine to openpyxl in from_excel

---

pandapower/control/run_control.py
pandapower/timeseries/run_time_series.py

as additional kwargs to run_control.py. This enables you to fire ctrl_repair if run_funct is not converging and that each level is checked for control convergence or not.

adding continue_on_divergence and check_each_level 

---

.github/workflows/github_test_action.yml

Remove codecov from flint, run 3.8 with codecov, closes #1108

Run tests for 3.8 with codecov

---

pandapower/create.py

Fit a type in docstring for `create_gen` #1125 .

fix typo in docs

---

pandapower/build_bus.py
pandapower/build_gen.py
pandapower/pd2ppc.py
pandapower/pf/runpp_3ph.py
pandapower/test/loadflow/test_runpp_3ph.py

This pull request will add a missing feature of initializing the state of the 3ph loadflow based on previous results.
Changes:
* Check existance of res_bus_3ph instead of res_bus
* Pass-through the sequence-parameter to get_voltage_init_vector
* Calculate the appropriate init vector for each sequence number
The calculation is slightly faster with these optimizations. Any remarks are highly appreciated.

Enable warm start for 3ph loadflow

---

CHANGELOG.rst
pandapower/control/controller/const_control.py

set the order and level to -1 by default in order to make sure that ConstControl runs before other controllers

const_control.py: set order and level to -1 as default

---

setup.py

fixes #1289
networkx>=2.5 is required to run pandapower under python3.9 because fractions module is deprecated in python 3.9

updated networkx dependency >=2.5 (see #1289)

---

LICENSE

Small spelling mistake, I am sure it is supposed to be "Fraunhofer Institute for Energy Economics" and not "Fraunhofer Institute for for Energy Economics".

fix typo in LICENSE

---

pandapower/create.py

The create_transformer function in create.py was not considering zero sequence parameters of the used std_type as described in the Docstring. Now it does.

Consider zero seq. params in create_transformer()

---

pandapower/converter/matpower/from_mpc.py
pandapower/converter/pypower/from_ppc.py

adding the extra data in a separate attribute is not very convenient, better add it to the net._options dict that gets overwritten at runpp. This way, the user can postprocess the additional data, if needed, and then the extra variables are discarded at power flow.

from_mpc.py: keep the extra data in net._options instead

---

.github/workflows/github_test_action.yml

drop 3.6 from github actions
adjust some conditional tests to use 3.7 instead of 3.6

drop Python 3.6

---

.github/workflows/github_test_action.yml
CHANGELOG.rst
doc/powerflow/ac.rst
pandapower/auxiliary.py
pandapower/pf/create_jacobian.py
pandapower/pf/create_jacobian_numba.py
pandapower/pf/makeYbus_numba.py
pandapower/pf/run_newton_raphson_pf.py
pandapower/pf/runpp_3ph.py
pandapower/pypower/makeYbus.py
pandapower/pypower/newtonpf.py
pandapower/run.py
pandapower/test/api/test_diagnostic.py
pandapower/test/api/test_toolbox.py
pandapower/test/converter/test_from_ppc.py
pandapower/test/loadflow/test_recycle.py
pandapower/test/loadflow/test_runpp.py
setup.py

added default "auto" option for lightsim2grid that decides whether to use it silently, added lightsim2grid to the GitHub CI for Python 3.9

lightsim2grid: changed checks for lightsim2grid

---

pandapower/pd2ppc_zero.py

Calculations of the zero-sequence impedances occur for more vector groups than are tested/implemented correctly for the 3ph power flow. Raise an error upon attempt to calculate runpp_3ph for unsoppiorted vector groups.
@gourab2009 @elodin

runpp3ph: raise error for unsupported vector group in runpp_3ph

---

pandapower/results_branch.py

For trafo vector groups with a gap in the zero seq. model (i.e. Dyn), the current calculation of the trafo lv side is special. It sums up the currents of the branch elements attached to it. Before, it was only considering elements that were attached with their FROM side. This led to wrong currents, when i.e. a line was attached the wrong way around, but gave no warning to the user.
Now, it also considers the TO side of elements, so lines can be attached either way and the trafo getting correct current results.

trafo_3ph lv current calc update

---

pandapower/auxiliary.py
pandapower/converter/powerfactory/logger_setup.py
pandapower/create.py

DataFrames used to be created in the function create_empty_network, but it is more convenient and more reasonable to do it in the constructor

pandapowerNet: create DataFrames at init; bugfix with StreamHandler

---

CHANGELOG.rst
pandapower/pypower/makePTDF.py
pandapower/test/loadflow/test_PTDF_LODF.py

This PR adds the functionality to restrict the PTDF computation to a subset of branches by adjusting the equation set to be solved.
As a consequence, computation time and resources are significantly decreased when only a subset of a grid model is of interest.
The ppci indices of the branches to be kept (positive list) is given in the optional keyword argument `branch_id`. Additionally, it is possible to reduce the size of the output matrix to these branches by setting `reduced=True`.

Partial computation of PTDF matrices in makePTDF.py

---

CHANGELOG.rst
pandapower/io_utils.py
pandapower/test/api/test_file_io.py
pandapower/test/api/test_toolbox.py
pandapower/toolbox.py
setup.py

Objective: to allow comparison of pandapower objects (e.g. Controller, Characteristic). Updated pp.toolbox.nets_equal to consider pp objects.

add method __eq__ to JSONSerializableClass 

---

CHANGELOG.rst
doc/powerflow/ac.rst
pandapower/auxiliary.py
pandapower/build_branch.py
pandapower/pf/create_jacobian_tdpf.py
pandapower/pf/run_newton_raphson_pf.py
pandapower/pypower/idx_brch_tdpf.py
pandapower/pypower/newtonpf.py
pandapower/results_branch.py
pandapower/run.py
pandapower/test/loadflow/test_tdpf.py
tutorials/temperature_dependent_power_flow.ipynb

TDPF: renaming r_theta to r_theta_pu and r_theta_kelvin_per_mw clarifies the code and makes it easier to avoid an error
init T from T0 
include r_theta_kelvin_per_mw in net.res_line

Tdpf results r theta

---

pandapower/build_branch.py

The new branch lookup order is causing problems with the IEEOptTool converter. Change it back to its original state to avoid problems

Change order back to original state

---

pandapower/grid_equivalents/get_equivalent.py
pandapower/grid_equivalents/rei_generation.py
pandapower/test/grid_equivalents/test_get_equivalent.py
pandapower/test/grid_equivalents/test_grid_equivalents_auxiliary.py
pandapower/toolbox.py

- the parameter "retain_original_internal_indices" is removed. The indices for all "internal" elements are kept. The new (equivalent) elements are numbered from the maximal index of the internal ones.
-  The dataframe column matching is improved.
1. the data type is recognized according to the data (e.g., `net.sgen.type.apply(type)`) , not the column (e.g., `net.sgen.type.dtype`). In this case, all columns are divided into five groups: **mixed**, **number**, **bool**, **str**, and **none**. 
2. if the data of one column have different types (e.g, string and None), the aggregated value is "mixed data type".
3. if the data of one column are all string and identical (e.g, "a", "a", "a"), the aggregated value is the same (e.g., "a").
4. if the data of one column are all string but different …

some improvements for grid equivalents

---

setup.cfg

By adding the attribute in setup.cfg, pytest will no longer complain about "unknown attribute 'slow'"

register pytest.mark.slow in setup.cfg

---

pandapower/io_utils.py

just like for deserialize_pandas and empty_dict_like_object, the registry_class can now be handed over directly to the Decoder to create the object_hook

JSON Decoder: added registry kwarg

---

pandapower/build_gen.py

This check also checks the ext grids.
I've added this to the error message so that the user also considers the ext_grid table before checking the gen table again and again...

Extend error message if diff. v setpoints

---

.readthedocs.yml

add matplotlib etc. to the readthedocs requirements
this is required because otherwise the create_collection functions cannot be imported and are not shown in the online documentation
(could help on #1566)

Update .readthedocs.yml, install plotting packages

---

doc/index.rst

This commit fixes pypower URL link in `doc/index.rst`.

Fix pypower link in index.rst

---

CHANGELOG.rst
pandapower/converter/cim/cim2pp/convert_measurements.py
pandapower/converter/cim/cim_tools.py

np.type dict is no longer supported under python 3.10 and numpy >= 1.24

fix deprecated np.typedict to np.sctypedict in cim converter

---

pandapower/plotting/__init__.py

Fix plotting bug

---

pandapower/io_utils.py

Hi,
since pandas version 2.10 read_json from literal (string) is deprecated. The message is really annoying and messes up logfiles.
Therefore this patch, which will wrap a string into an StringIO object (as recommmended by the pandas people). Probably it will also be faster?
BR

pandas deprecation fix for read_json

---

pandapower/plotting/geo.py
pandapower/test/helper_functions.py

fixed create_test_network using numpy.array for geocoords eventhough the doc calls for list
fixed issue in geo.py resulting from #2138
updated deprecated pyproj.transform to pyproj.Transformer in geo.py
ran all test: 995 passed, 51 skipped, 16 xfailed, 1169 warnings
No warnings come from changes implemented in this PR.

fixes #2138

---

CHANGELOG.rst
pandapower/converter/cim/cim2pp/build_pp_net.py
pandapower/converter/cim/cim2pp/convert_measurements.py
pandapower/converter/cim/cim2pp/converter_classes/coordinates/coordinatesFromDLCim16.py
pandapower/converter/cim/cim2pp/converter_classes/coordinates/geoCoordinatesFromGLCim16.py
pandapower/converter/cim/cim2pp/from_cim.py
pandapower/converter/cim/cim_classes.py
pandapower/converter/cim/cim_tools.py
pandapower/converter/cim/serialized_schemas/CIM16_4.0.8_schema.json

cim2pp: extracted getting default classes, added generic setting datatypes from CGMES XMI schema

---

pandapower/auxiliary.py

This pull request addresses the bug identified in the plural_s function within the pandapower project. The issue occurs when attempting to pluralize a word based on a given number. The current implementation incorrectly returns an empty string when the number is greater than 1, indicating the plural form. The fix ensures that the function now correctly returns an empty string for numbers equal to or less than 1, and "s" for numbers greater than 1.
Modified the plural_s function to correctly handle pluralization based on the input number.
Issue opened number #2180

Resolving simple bug [bug] Incorrect Pluralization in plural_s Function (Simple) #2180

---

pandapower/control/controller/trafo/ContinuousTapControl.py
pandapower/control/controller/trafo/DiscreteTapControl.py

if trafos are set out of service by connectivity check, the result is NaN, which leads to convergence problems of tap controllers --> fixed with this change

fix NaN in tap controllers

---

CHANGELOG.rst
pandapower/pypower/makeLODF.py
pandapower/test/loadflow/test_PTDF_LODF.py

Key Points
*    makeOTDF:
Calculates the Outage Transfer Distribution Factors (OTDF) matrix.
Connects bus power injections to branch flows for outage scenarios.
Inputs: PTDF matrix, LODF matrix, and outage branch indices.
Output: OTDF matrix tailored for N-1 contingency analysis.
*    outage_results_OTDF:
Computes branch power flows for each defined outage scenario using OTDF.
Inputs: OTDF matrix, bus power vector (Pbus), and outage branch indices.
Output: Array of branch power flows under each outage scenario.
*    Testing and Validation
Tested against contingency analysis with pp.rundcpp
*    Application
Useful for fast contingency analysis in power systems when DC approximation is acceptable.

add function to compute OTDF and evaluate outages using OTDF

---

pandapower/create.py

The usage of intersect1d instead of isin leads to massive speed-up when providing an index to be used inside the bulk create functions.

speed-up of multi-index check in create functions

---

pandapower/results_branch.py

Running pp.runpp_3ph fails with a key error if trafo index is not starting at 0 or it is not consecutive.
Minimal example:
```python
import pandapower as pp
import pandapower.networks as nw
net = nw.ieee_european_lv_asymmetric("on_peak_566")
net.trafo.loc[1] = net.trafo.loc[0]
net.trafo.drop(0, inplace=True)
pp.runpp_3ph(net) # -> KeyError: 0
```
Fixed by this PR.

fix key error in unbalanced powerflow if trafo index is not consecutive or not starting at zero

---

CHANGELOG.rst
pandapower/diagnostic.py

`pp.diagnostic` runs power flows during various tests but does not allow passing arguments to `pp.runpp`. 
This PR adds an optional argument `runpp_function` to `pp.diagnostic` which takes a function to be used for running power flows. The argument defaults to `pp.runpp`, existing code is unaffected.
Arguments to `pp.runpp` can then be passed through `pp.diagnostic` by supplying a partial as the `runpp_function`.

Feature: allow passing custom runpp-function to pp.diagnostics

---

pandapower/plotting/plotly/traces.py

Fix for the following issue: Results might fail to plot with `pf_res_plotly` due to empty x/y coordinate data arrays by KeyError on non-existing lon/lat fields.

avoid KeyError Exeption on traces with empty x/y coordinate array and missing lon/lat field

---

CHANGELOG.rst
pandapower/converter/cim/cim_classes.py

Hi all, 
after aligning with Mario Stefan Richter, here a change as a preparation for using cgmes 3.0. 
The CimParser get cim data structure has been changed to create a blueprint cim data structure while initializing. This blueprint data structure is protected by name mangling and uses MappingProxyTypes (read only dictionaries). This data structure is now defaulting to cim16, but extendability to cim100 (cgmes 3.0) is included. 
The get_cim_data_structure method has been changed to return a nested dictionary with a deep copy of every Dataframe of the blueprint data structure. 
Performance increase of the get_cim_data_structure function over the _initialize_cim16_data_structure function is significant (~0.05 seconds vs ~0.02 seconds in local tests). No significant performance difference …

Implement blueprint approach for initializing cim data structure in cim converter

---

pandapower/grid_equivalents/rei_generation.py

This snippet of code speeds up the reodering of Y_bus_origin to Y_bus_sorted in rei_generation.py by using vector operations instead of nested for loops. Original code was slow when getting an equivalent for large grids.

vectorization of y_bus reordering in _calculate_equivalen_Ybus

---

pandapower/converter/powerfactory/pp_import_functions.py

During import from pandapower, the status of outserv of the coresponding station controller needed to be taken into account. Also, support of 2 imode for reactive power distribution were not considered. Changes now lead to better results during import from power factory

BugFix in PF converter for station controller

---

CHANGELOG.rst
pandapower/build_branch.py
pandapower/pf/run_bfswpf.py
pandapower/shortcircuit/ppc_conversion.py
pandapower/shortcircuit/toolbox.py
pandapower/test/loadflow/test_results.py
pandapower/topology/create_graph.py

This PR removes many warnings:  `DeprecationWarning: in1d is deprecated. Use np.isin instead.`
`isin` in contrast to `in1d`: return the same shape as [`element`](https://numpy.org/doc/stable/reference/generated/numpy.isin.html#numpy.isin)
```
element = np.array([[0, 1, 2, 5, 33], [3, 7, 12, 15, 10]])
test_elements = [0, 2, 15]
```
isin
`print(np.isin(element, test_elements))`
Output
```
[[ True False  True False False]
[False False False  True False]]
```
in1d
`print(np.in1d(element, test_elements))`
Output
`[ True False  True False False False False False  True False]`

Replacing deprecated in1d with isin

---

CHANGELOG.rst
pandapower/converter/cim/cim2pp/build_pp_net.py

This fixes #1905 
When pandapower is imported, it changes the pandas options `display.max_rows` and `display.max_columns`, as the following example demonstrates:
```python
import pandas
pandas.get_option('display.max_rows')
pandas.get_option('display.max_columns')
import pandapower
pandas.get_option('display.max_rows')
pandas.get_option('display.max_columns')
```
This is rather annoying especially since it often leads to long waiting time if one is printing a large DataFrame.
The reason are the following two lines in the file `pandapower/converter/cim/cim2pp/build_pp_net.py`:
```python
pd.set_option('display.max_columns', 900)
pd.set_option('display.max_rows', 90000)
```
The pull request removes those lines and fixes the problem.
```python
import pandas …
```

don't change pandas options when importing pandapower

---

pandapower/converter/cim/cim2pp/from_cim.py
pandapower/converter/cim/cim_classes.py

Fix for issue #2419, changes default value of "encoding" keyword argument to None for parse_files() and from_cim().

Change default value of encoding argument in converter methods #2419

---

.github/workflows/github_test_action.yml
doc/requirements.txt
pyproject.toml

The e2niee/sphinx-action clone (used to make sure documentation can be build) uses the [latest sphinxdoc/sphinx image](https://github.com/e2nIEE/sphinx-action/blob/1c785bcbb732cc38e1c573106af98332605f43ac/Dockerfile#L1) available. 
But one day that means running python 3.13, and numpy has no wheels for it yet, but to build them requires libraries missing in the python-slim base image, and that is how you end up installing the fortran compiler just to build docs and the whole thing takes 10 minutes to complete.
Switching sphinx-action back to upstream and pinning the sphinx image version to 7.4.7 (and python 3.12) makes the doc_test job complete in ~45s.

GA: fix docs_check job

---

.github/workflows/upload_release.yml
pandapower/_version.py
pyproject.toml

set version number for the develop branch to include a dev release suffix.
added a workflow dispatch section
added a upload to testpypi section

dev releases and workflows

---

doc/elements/line_par.csv
pandapower/create.py

I found small errors in the doc:
- For the lines the parameter x_ohm_per_km corresponds to the reactance of the line and not its inductance (else the unit would have been h_per_km)
- In the docstring of the create_load and create_loads functions the parameter p_mw was described as optional and defaulting to 0, but it is not (but maybe it should ?)
Also there is a contradiction between the comment in this docstring that says that a negative load can be used to model a static generator, and the note in the documentation: "Loads should always have a positive p_mw value, since all power values are given in the consumer system. If you want to model constant generation, use a Static Generator (sgen element) instead of a negative load.".
Is using a load with a negative p_mw equivalent to using a …

Doc correction

---

pandapower/plotting/plotly/traces.py

plotly changed the interface and renamed the titlefont property.

---

CHANGELOG.rst
pandapower/results_bus.py
pandapower/test/loadflow/test_rundcpp.py

If an dc loadflow is run after an ac loadflow, "old" results are still present, even if they do not make sense.

[fix] DC loadflow after AC loadflow

---

CHANGELOG.rst
pandapower/converter/powerfactory/pp_import_functions.py

Wrong value was selected during import (maximum temperature instead of operating temperature). Corrected it. Also on the way I removed the "control." in the pf2pp converter.

[FIX] Corrected import of line temperature in the pf2pp import

---

doc/conf.py
doc/plotting/plotly/geo_data_to_latlong.rst
pandapower/contingency/contingency.py
pandapower/control/controller/DERController/der_control.py
pandapower/converter/jao/from_jao.py

fixed some issues in docs compilation
fixed docstring not showing in docs because of incorrect headings
Fixed all errors from the latex doc build.
Found section not compiling to html or latex doc as it used `INPUT` and `OUTPUT` instead of `Parameters` and `Returns`. Updated it for Consistency to the `:param type name:` docstring.

Minor fixes to the docs

---

pyproject.toml

Since pip 21.2 recursive optional dependencies are possible. So here is a pr that adds this in pandapower.
- changed the all group to use recursive dependencies to avoid forgetting to define new dependencies twice

Updated toml

---

pyproject.toml

added a tools.black section to the toml for any black config. So that all users using black have a consistent config.
This does not force anyone to use black, nor does it change anything in the pipelines! It only affects the behavior of black if it is used by the individual developer.

added some config for black users

---

.github/workflows/github_test_action.yml
.github/workflows/test_release.yml
CHANGELOG.rst
pyproject.toml

Add python 3.13 to github workflow files and pyproject.toml
I'm not sure what to do with python version in some jobs: the version is neither the minimal supported nor the latest. Should they also be updated or is there a particular reason to keep them pinned? Versions in question:
* `linting` https://github.com/e2nIEE/pandapower/blob/0260bf693dbbb2ac067e38df5012242bb41b51f6/.github/workflows/github_test_action.yml#L197
* `tutorial_tests` https://github.com/e2nIEE/pandapower/blob/0260bf693dbbb2ac067e38df5012242bb41b51f6/.github/workflows/github_test_action.yml#L296
* `tutorial_warnings_tests` https://github.com/e2nIEE/pandapower/blob/0260bf693dbbb2ac067e38df5012242bb41b51f6/.github/workflows/github_test_action.yml#L320

Add python 3.13 support

---

pandapower/plotting/plotly/pf_res_plotly.py

Pf_res_plotly function has no checks if net element has ext_grid element or not. Creates an error when no ext_grid Element is in network.
Easy fix for more robustness

pf_res_plotly throws error when no ext_grid element in net obj

---

doc/elements/bus_res_3ph.csv

Code is correct, but there's a problem with doc.
As per IEC Unbalance Voltage = V2 / V1, which is correct in code:
https://github.com/e2nIEE/pandapower/blob/develop/pandapower/results_bus.py#L71
However, in doc it was stated as V0 / V1.

Correct Doc of res_bus_3ph Unbalance Percent.

---

pandapower/test/consistency_checks.py
pandapower/test/loadflow/test_runpp_3ph.py

PR #2720 fixed the transformer power and current consistency problems. One of the key change was applying negative shift in case of negative sequence. But current tests created in `loadflow/test_runpp_3ph.py::test_trafo_asym__with_shift` only worked with rtol=1e-1 (hardcoded in `trafo_currents_consistent_3ph` function in consistency_checks.py) and also the test worked for both positive and negative shift in negative sequence due to low rtol value.
Now I've updated the test network with a simple network in `test_trafo_asym_currents__high_neg_seq` and made shunt admittance of transformer 0 in both positive and zero sequence so shunt currents do not disturb our consistency checks. With this change, the tests are now working with **rtol=1e-9**, also the test now fails if shift is not reversed …

Improved tests for Trafo 3ph current consistency
