e2nIEE/pandapower

pandapower/toolbox.py

drop elements connected to certain buses and drop the buses as well

drop_elements_at_buses function

---

pandapower/plotting/plotly/get_colors.py

I got an `np not defined` error using `pandapower.plotting.plotly.vlevel_plotly`
This should fix..
Lee

import numpy (line 40)

---

pandapower/test/api/test_toolbox.py
pandapower/toolbox.py

Dear Mr. Thurner,
These are the changes in toolbox.py and tests for the functions: drop_elements_at_buses() , next_bus () and get_connected_buses()

Changes on 3 functions and tests for them

---

doc/getting_started/introduction.rst

I realized that there's just four places that needed to be changed and made the following PR. I was able to generate the documentation locally to check that this worked. Fixes #103.

Fix documentation links

---

pandapower/topology/create_graph.py

For some analysis it is helpfull to have a measure of the electrical distance between buses and not only the length distance. Especially for networks with lots of impedances having only a weight of zero is not helpfull.
Be aware that I do not use the values directly so I am not 100 percent shure if my calculations are correct, please have a good look at the formulas I used. It gives reasonable results for the functionality I need though.

Add resistance and impedance as weights to graph

---

pandapower/build_bus.py
pandapower/build_gen.py
pandapower/create.py
pandapower/pd2ppc.py
pandapower/test/loadflow/test_runpp.py

Allow multiple generators at a bus

---

pandapower/build_branch.py

Check for zero impedance in equivalent trafo

---

pandapower/results_branch.py

Since I already added the fix anyway...
Closes #137

silence warning for transformers and switches without results

---

pandapower/plotting/collections.py
pandapower/toolbox.py

some old grids had 0 as tp_side, this is also converted now
enable passing specific buses and ext_grid indices to create_ext_grid_collections for the case when separate collections should be created for specific ext_grids

toolox._pre_release_changes; collections.create_ext_grid_collection

---

pandapower/pf/run_newton_raphson_pf.py
pandapower/run.py
pandapower/test/api/test_diagnostic.py
pandapower/test/loadflow/test_runpp.py

- add recycle to **kwargs #122 
- power flow for networks without branches #157

runpp developments

---

CONTRIBUTING.rst

small fix in doc changed gitconfig to git

---

pandapower/build_branch.py
pandapower/create.py
pandapower/test/loadflow/test_scenarios.py

The _switch_branches function needs to be refactored ASAP (see #30), but since it doesn't seem like we currently have the time to do that, I included switches for three-winding transformers in the current design for now.

switches at three winding transformers #30

---

pandapower/diagnostic.py
pandapower/test/api/test_diagnostic.py

old: 0<=x<=1 new: 0<x<=1. Additionally some minor naming changes + according changes to test_diagnostic

diagnostic: changed invalid values check for line derating factors

---

pandapower/shortcircuit/kappa.py

...plus some automatic mixed line endings corrections by GitHub.

Minor typo

---

pandapower/estimation/wls_ppc_conversions.py
pandapower/test/estimation/test_wls_estimation.py

Fixed bug in state estimation on network with disconnected branches

---

pandapower/io_utils.py
pandapower/opf/printpf.py
pandapower/optimal_powerflow.py

 include PYPOWER logging for OPF for verbose=True

---

pandapower/__init__.py
pandapower/networks/mv_oberrhein.py
pandapower/networks/power_system_test_cases.py
pandapower/plotting/plotly/mapbox_plot.py
pandapower/runpm.py
pandapower/test/api/test_file_io.py
pandapower/test/converter/test_from_mpc.py
pandapower/test/converter/test_from_ppc.py
pandapower/test/estimation/test_wls_estimation.py
pandapower/test/loadflow/test_runpp.py
pandapower/test/shortcircuit/test_1ph.py
pandapower/test/shortcircuit/test_meshing_detection.py
pandapower/test/toolbox.py

to simplify and unify path handling within pandapower

set all paths from pp_dir

---

pandapower/estimation/estimator/wls.py
pandapower/estimation/idx_bus.py
pandapower/estimation/ppc_conversions.py
pandapower/estimation/state_estimation.py
pandapower/test/estimation/test_wls_estimation.py

Added the enhancement mentioned in #277 
Added test case

Added more flexibility in parameter zero injection bus and buses with bb-switches to be fused

---

pandapower/test/topology/test_graph_searches.py
pandapower/topology/graph_searches.py

Make elements_on_path work with graph keys as defined in #85

elements on path with new nx key definitions

---

pandapower/build_branch.py
pandapower/test/loadflow/test_scenarios.py

Appending the auxiliary buses only in the end creates a problem for transformers with switches at both sides, because the necessary auxiliary buses do not yet exist inside the loop

fix open switches at both sides of transformer

---

pandapower/toolbox.py

improve toolbox function add_column_from_element_to_elements() docstring and error handling

tiny toolbox function improvement

---

pandapower/plotting/collections.py

This is the fix mentioned in issue #302

Add Fix for switch positions on lines #302

---

pandapower/create.py
pandapower/test/opf/test_costs_pwl.py

New docstrings for cost functions in create.py

 New docstrings for cost functions in create.py 

---

pandapower/build_branch.py
pandapower/test/estimation/test_wls_estimation.py
pandapower/test/loadflow/test_runpp.py
pandapower/test/shortcircuit/test_1ph.py

Refactor ppc handling #282

---

pandapower/networks/simple_pandapower_test_networks.py

Reactive power changed between 1.x and 2.x

Fix simple_four_bus_system

---

pandapower/create.py
pandapower/test/opf/test_basic.py
pandapower/test/opf/test_cost_consistency.py
pandapower/test/opf/test_costs_mixed.py
pandapower/test/opf/test_costs_pwl.py
pandapower/test/opf/test_costs_pwl_q.py
pandapower/test/opf/test_dcline.py
pandapower/test/opf/test_powermodels.py

pwl costs as list instead of tuples

---

pandapower/toolbox.py

convert format: fix for issue #308

---

pandapower/estimation/state_estimation.py

removed deprecated docstring for "chi2_prob_false" in estimation

---

pandapower/pf/run_newton_raphson_pf.py

small fix to consider type of option va_degree in runpp (_run_newton_raphson)

fix for option init_va_degree

---

pandapower/test/topology/test_graph_searches.py
pandapower/topology/graph_searches.py

fixed identification of stub buses for some egde cases and added a test

---

pandapower/test/pytest.ini

Mentioned here:
https://github.com/scipy/scipy/issues/9734

pytest ini with slow marker and filter for scipy warnings

---

pandapower/topology/graph_searches.py

Just a very tiny change to be quicker in requesting the status of a bus in the graph search unsupplied_buses

changed loc to at in checking if buses in service (unsupplied_buses)

---

doc/plotting/matplotlib/create_colormaps.rst
pandapower/plotting/colormaps.py
pandapower/test/plotting/test_create_colormaps.py
pandapower/test/plotting/test_to_html.py

I added a convenience function to add logarithmic colormaps as discussed in #360 . Tests and documentation is added as well, just a jupyter notebook introduction is missing by now.

added a convenience function for creating logarithmic colormaps

---

doc/elements/sgen.rst
pandapower/create.py

Hi.
This refers to issue #372. I've made small corrections to reflect the new generator convention in the following docstrings and file:
- create_sgen
- create_sgen_from_cosphi
- create_gen
- sgen.rst

Update of the docstrings of create_sgen, create_gen

---

pandapower/topology/graph_searches.py

removed parameter in_service_only from unsupplied_buses

---

doc/powerflow/diagnostic.rst
doc/topology/examples.rst
pandapower/toolbox.py

Some lines seem to have spaces and the commit replaces them with an empty line. I didn't want to include those lines into the commit but the fix happens automatically.

updated topology example to pandapower 2.0, added unit to logging output of function lf_info

---

CHANGELOG.rst
doc/opf/powermodels.rst
pandapower/build_branch.py
pandapower/opf/run_powermodels_ac.jl
pandapower/opf/run_powermodels_dc.jl
pandapower/opf/run_powermodels_tnep.jl
pandapower/runpm.py
pandapower/test/opf/test_powermodels.py
pandapower/test/test_files/run_powermodels_custom.jl
tutorials/tnep_powermodels.ipynb

This pull request is an interface to the TNEP optimzation methods of PowerModels.

PowerModels TNEP interface, jupyter notebook and test

---

pandapower/file_io.py

Hi,
This refers to issue #410. I've made some updates in the docstrings of the following functions of the module file_io:
- *from_pickle*;
- *from_excel*;
- *from_json*;
- *from_json_string*;
- *from_json_dict*;

Update of the docstrings of file_io.py

---

pandapower/pypower/makeLODF.py
pandapower/pypower/makePTDF.py
pandapower/test/loadflow/test_PTDF_LODF.py

Add both modules with slight modification to avoid numpy type warning and zero division error under N-1 contingency, in case of sensitivity analysis

Added makePTDF, makeLODF Pypower module 

---

pandapower/test/api/test_toolbox.py
pandapower/toolbox.py

Fixing #439, fixed element index in measurements table when reindexing elements (branches)

Fix of #439

---

doc/control.rst
doc/control/building_a_controller.rst
doc/control/cascade_control.rst
doc/control/control_loop.rst
doc/control/timeseries.rst
doc/control/tutorials.rst
doc/estimation.rst
doc/index.rst
doc/opf.rst
doc/pics/control/cascade_control.svg
doc/pics/control/run_timeseries_reglerstrecke.svg

Updating and Adding Control and Timeseries Documentation due to the brandnew control and timeseries modul in pandapower.

Updating and Adding Control and Timeseries Documentation

---

pandapower/converter/matpower/to_mpc.py

Make baseMVA type float for export to matpower

---

pandapower/estimation/state_estimation.py

For example:
from pandapower.estimation import estimate
import pandapower.networks as nw
net = nw.simple_four_bus_system()
estimate(net, algorithmus="lp")
>>>>hp.pandapower.estimation.state_estimation - WARNING: Caution! algorithmus is not allowed 
as parameterfor estimate and will be ignored!
It now gives a warning because of the unknown parameter "algorithmus"

Added parameter check in the state estimation module and gives a warning if unknown parameter given

---

pandapower/io_utils.py

hook for PPJSONDecoder can be overwritten; adaptable hook for JSONSerializables

adaptations for yet more flexible json encoding and decoding

---

doc/opf/powermodels.rst

The suggested solution in the warning message has been merged upstream (see https://github.com/JuliaPy/pyjulia/pull/324).

PowerModels: Removed warning about pyjulia bug (fixed upstream)

---

doc/networks/kerber.csv
doc/networks/kerber.rst
doc/networks/kerber_extreme.csv
pandapower/networks/kerber_extreme_networks.py
pandapower/networks/kerber_networks.py

The net.load.p_mw values of some of the kerber/-extreme nets were incorrect. They are now adjusted.

fix p_mw of several kerber and kerber extreme grids #500

---

doc/control/control_loop.rst
doc/control/tutorials.rst
tutorials/control_loop.ipynb

Small update due to the newest changes. Adding a short tutorial

Adding a short control-loop tutorial and updating control docu

---

pandapower/networks/mv_oberrhein.py
pandapower/test/networks/test_mv_oberrhein.py

#539 Was failing due to incorrect import statement.
@jwiemer112 
@SteffenMeinecke

Added separation by substation feature for MV Oberrhein Pt. 2

---

pandapower/run.py

avoid extra power flow with controllers

---

pandapower/timeseries/run_time_series.py

revert run_control vs. runpp() in run_tim_series

---

doc/elements/xward.rst

Typo I think. Probably copy-paste error.

change heading to Input

---

pandapower/converter/matpower/to_mpc.py

add mpc dict to to_mpc() converter

---

pandapower/plotting/collections.py

use .loc to access coords in a dataframe

bugfix coords in line collections

---

pandapower/test/shortcircuit/test_1ph.py
tutorials/time_series.ipynb
tutorials/time_series_advanced_output.ipynb

Avoid creating default output variables.
Fixed some typos.

Add log_variables parameter to OutputWriter constructor call

---

pandapower/io_utils.py
pandapower/test/api/test_toolbox.py
pandapower/test/timeseries/test_output_writer.py

 time_steps to Iterable and index in recycle output 

---

pandapower/test/topology/test_graph_searches.py
pandapower/topology/graph_searches.py

add topological distance to calc_distance_to_bus (weight=None)

---

tutorials/shortcircuit_renewables.ipynb

Updated link and code

---

CHANGELOG.rst
pandapower/create.py
pandapower/toolbox.py
pandapower/topology/create_graph.py

…ch indices in create_nxgraph()

create_nxgraph(): add dclines and considering given branch indices

---

pandapower/estimation/util.py

Dear admin,
I found a little bug in the function definition for the creation of virtual measurement for the state estimation.
They were basically about the parameter in the call of the method:
add_virtual_meas_error
Best,
Andrea

fix default parameters

---

pandapower/auxiliary.py
pandapower/test/api/test_auxiliary.py

The issue of copy.deepcopy(net) not properly copying objects in DataFrames is solved

changed net.__deepcopy__ back to using copy.deepcopy

---

pandapower/plotting/plotly/traces.py

Modified _in_ipynb() method in plotting/plotly/traces. Following @gusutabopb [advice on StackOverflow](https://stackoverflow.com/a/39662359/12859792), the new method seems more general and exact.

Modified _in_ipynb() method to a more general case.

---

doc/opf/pypower_run.rst
pandapower/create.py
pandapower/run.py
pandapower/toolbox.py

+ small corrections in documentation

select_subnet now removes results if not required (to close #746); 

---

pandapower/plotting/collections.py

the linewidth of a patch in a e.g. node_element didn't change so far, when adapting the linewidth of the rest of the collection. Now, the linewidth of the patch is adapted, too.

linewidth patch

---

pandapower/plotting/simple_plot.py

The order of the input variables in get_collection_sizes in simple_plot.py is wrong

wrong order input data in simple_plot.py

---

README.rst

Incorrect batch references for codecov and codacy have been adapted.

adapting the batches for codacy and codecov

---

doc/elements/line_res.csv
pandapower/create.py
pandapower/shortcircuit/results.py

short-circuit result tables

---

README.rst

binder badge, hints and logos for pandapipes and simbench added in readme

Readme update with logos

---

pandapower/create.py
pandapower/plotting/collections.py
pandapower/plotting/plotly/pf_res_plotly.py
pandapower/test/api/test_toolbox.py
pandapower/toolbox.py

-> slidely changed behaviour of fuse_buses()

inner branches consideration in fuse_buses()

---

pandapower/plotting/generic_geodata.py

partially mitigates e2nIEE/pandapower/#781

more user friendly igraph exception

---

README.rst

* scaling of png files seems to have no effect on github but on pypi
* width of 25em was not readable

increase scaling of 2 logos in README.rst

---

CHANGELOG.rst
doc/networks.rst
pandapower/toolbox.py

revision of drop_out_of_service_elements() and and new drop_measurements_at_elements()

consider measurements in toolbox functions

---

pandapower/pypower/makeBdc.py
pandapower/pypower/makeLODF.py
pandapower/pypower/makePTDF.py
pandapower/test/loadflow/test_PTDF_LODF.py

Added csc/csr selection for MakeBdc
Added sparse solver support for PTDF
Silence Warnings in LODF

Improvement in MakeBdc/PTDF/LODF

---

pandapower/estimation/results.py
pandapower/test/estimation/test_opt_lp_estimation.py

Fixed #803 and simplify tests for estimation

---

pandapower/io_utils.py

adaptions in pp_hook, to make it more modular and better for pandapipes

adaptions of pp_hook

---

pandapower/io_utils.py

small adaptions in order to reduce unnecessary code

Adaption pp hook

---

pandapower/control/controller/const_control.py

A bug in the const controller when scaling values are set and recycle = True in a time series simulation is fixed by this commit

fix #850 recycle of scaling value

---

pandapower/io_utils.py

A Test failed when geopandas objects are included in a net. Was not detected by the tests as geopandas is not installed on the server. Now the bug should be fixed.

Bugfix io utils

---

pandapower/io_utils.py

Clean control 2.0

---

pandapower/convert_format.py

the original code will reset sn_mva if "sn_kva" not available in the network, which is not the wished behavior

Bug fixing in convert_format to avoid automatic reset of sn_mva

---

pandapower/control/run_control.py
pandapower/converter/powermodels/to_pm.py
pandapower/test/opf/test_pp_vs_pm.py

https://github.com/e2nIEE/pandapower/issues/911
.. and some cleanup

Fixing #911

---

pandapower/test/opf/test_TNEP.py

adding test for powermodels TNEP functionality

---

.travis.yml

Add testing with Python 3.8 with TravisCI

added testing with Python 3.8 to TravisCI

---

doc/elements/impedance_par.csv
doc/elements/line_res_3ph.csv
pandapower/pd2ppc_zero.py
pandapower/pf/runpp_3ph.py

Remove some typos
Fix documentation of function runpp_3ph

Minor documentation fix

---

pandapower/toolbox.py

added full element names to some functions, expanded get_connected_buses_at_element

toolbox: imporoved get_connected_buses_at_element

---

pandapower/create.py

Fixed multiple typo in create element

---

pandapower/create.py
pandapower/test/api/test_file_io.py

replaces ... = Series() by Series(dtype=float64)

create: explicitly set dtype for Series to silence DeprecationWarning

---

doc/estimation.rst

Since now state estimation uses the same signing system as the rest of pandapower. We can safely delete this.

Updated description in estimation to fix #999

---

pandapower/estimation/algorithm/base.py

The code in line 138 does not follow the current version of numpy.

BUG again in WLSZeroInjectionConstraintsAlgorithm

---

pandapower/pf/runpf_pypower.py
pandapower/pf/runpp_3ph.py

If recycle is False, no error will be raised.
recycle  = None or False will lead to the same result now.

Change the way recycle is checked

---

pandapower/control/basic_controller.py
pandapower/control/controller/const_control.py
pandapower/control/controller/trafo_control.py
pandapower/control/run_control.py
pandapower/convert_format.py
pandapower/create.py
pandapower/timeseries/run_time_series.py

moving initial_run/recycle solely to net.controller

Initial run

---

MANIFEST.in

Release 2.5.0

---

CHANGELOG.rst
pandapower/io_utils.py

fragments in changelog

---

pandapower/control/basic_controller.py

unfortunately removed matching_params --> bugfix

bugfix matching params

---

pandapower/plotting/plotting_toolbox.py

coords_from_node_geodata now accepts kwarg to ignore zero length branches

Small adaptation for creating branch collections from node geodata

---

pandapower/io_utils.py
pandapower/test/api/test_file_io.py

bugfix in io_utils GeoDataFrame

bug io_utils

---

.github/workflows/github_test_action.yml

remove python 3.5 tests from github actions

---

pandapower/converter/pypower/to_ppc.py
pandapower/create.py
pandapower/estimation/algorithm/base.py
pandapower/estimation/algorithm/estimator.py
pandapower/estimation/algorithm/lp.py
pandapower/estimation/algorithm/matrix_base.py
pandapower/estimation/algorithm/optimization.py
pandapower/estimation/ppc_conversion.py
pandapower/estimation/state_estimation.py
pandapower/estimation/util.py
pandapower/pypower/makeLODF.py
pandapower/pypower/makePTDF.py

Removed signing warning of P,Q on buses, fixed #1129

---

CHANGELOG.rst
pandapower/estimation/algorithm/lp.py
pandapower/test/estimation/test_opt_lp_estimation.py
setup.py

LAV estimator works slow (#1210) with large network sizes due to scipy linprog method. There is an alternative, OR-Tools, which is open source, and it can boost the performance.
This request implements OR-Tool beside the scipy's linprog. If OR-Tools is installed, the program uses it. Otherwise, scipy linprog is used as in the current version. Two additional tests are provided.

Integrating OR-Tools for linear programming solution of LAV

---

.github/workflows/github_test_action.yml

add Python 3.9 to GitHub Actions Testing

add Python 3.9 to GitHub Actions Testing

---

CHANGELOG.rst
doc/control/controller.rst
pandapower/control/controller/const_control.py

* write_to_net during time_step instead of control_step 
* removed initialize_control bacause no need

const_control.py: write_to_net during time_step 

---

pandapower/io_utils.py
pandapower/plotting/geo.py
pandapower/test/api/test_file_io.py

new method: "epsg:31467" instead of from_epsg(31467)
reason: deprecation warning from geopandas

remove fiona.crs.from_epsg -> deprecation warning

---

pandapower/plotting/simple_plot.py

fixes #1322 
(added docstring for plot_gens)

simple_plot: added docstring for plot_gens

---

pandapower/converter/powermodels/to_pm.py
pandapower/test/opf/test_powermodels.py
pandapower/test/opf/test_pp_vs_pm.py

fix the test for current mode, test_pp_vs_pm. It needs to update PandaModels.jl

current limit opf model

---

pandapower/pf/run_bfswpf.py
pandapower/pf/run_dc_pf.py
pandapower/pf/run_newton_raphson_pf.py
pandapower/pf/runpf_pypower.py
pandapower/pf/runpp_3ph.py
pandapower/pypower/opf.py
pandapower/timeseries/output_writer.py

Pull request related to issue #1396

using perf_counter instead time.time() for more accurate time measurments

---

pandapower/io_utils.py
pandapower/test/api/test_file_io.py

save numpy objects with signature in JSON encoder 

---

pandapower/pypower/newtonpf.py

See #1409 for more information

Update newtonpf.py: better initialization of slack power

---

tutorials/powerflow.ipynb

added hint on option rules to loadflow tutorial

---

pandapower/io_utils.py
pandapower/toolbox.py

All pandas.testing imports now implemented with fallback to pandas.util.testing to close #648

Pandas testing import

---

pandapower/timeseries/output_writer.py

enable reading results for 3ph power flow: line -> res_line_3ph

output_writer: enable saving from res_line_3ph etc. tables

---

pandapower/test/timeseries/test_timeseries.py
pandapower/timeseries/run_time_series.py

* remove passing of output_writer, 
* adjust tol, 
* add tests for pf options

test for time series simulation: 

---

pandapower/create.py

add the key "OPF_converged" in create.py

---

pandapower/pd2ppc_zero.py

use lowercase for vector groups to also accept "wrong" notation of vector groups

pd2ppc_zero: accept vector_group even if it is written incorrectly.

---

pandapower/test/api/test_toolbox.py
pandapower/toolbox.py

fixes #1592 
Added test  that reproduces the issue
Fixed the bug in the function get_connected_elements

bugfix for get_connected_elements_dict; fixed FutureWarning; fixes #1592

---

CHANGELOG.rst
pandapower/file_io.py
pandapower/io_utils.py
pandapower/test/api/input_files/test_control.py
pandapower/test/api/test_file_io.py

if e.g. a path changes, you can pass a dict to replace the changed elements

Replace json elements

---

CHANGELOG.rst
pandapower/plotting/collections.py
pandapower/plotting/simple_plot.py

* neccessary to properly plot transmission networks that include HVDC connections

add dcline collections, also in simple_plot

---

doc/elements/trafo.rst

This pr is following [this discussion.](https://github.com/e2nIEE/pandapower/discussions/1438)
Here is the preview of the note added :

specification on vkr_percent parameter

---

pandapower/toolbox.py

replace_impedance_by_line: index of impedance and not of line

bugfix typo

---

.readthedocs.yml

I've tried it on RTD, this should work now

fix RTD requirements

---

CHANGELOG.rst
pandapower/plotting/plotly/simple_plotly.py
pandapower/plotting/plotly/traces.py

plus:
+ make legend item size constant simple_plotly
+ make line width etc. in simple_plotly floats
+ check if trafos, ext_grids exists before trying to create respective traces in plotly

several sizes + color for scale legend in weighted_marker_trace

---

.github/ISSUE_TEMPLATE/config.yml

Remove the option to open blank issue to motivate people to use the issue templates.

add config.yml to ISSUE_TEMPLATE

---

pandapower/pypower/opf_consfcn.py
pandapower/pypower/opf_hessfcn.py
pandapower/pypower/totcost.py
pandapower/timeseries/data_sources/frame_data.py

fixed np.int64 error with numpy import

Bugfixes for 2_12_1 #1989

---

CHANGELOG.rst
pandapower/estimation/util.py
pandapower/test/estimation/test_wls_estimation.py

change dc to ac pf, run pf after estimation to allow comparison between res_bus & res_bus_est, update change log

fix estimation tests resulting from bug fix #2017

---

doc/shortcircuit/currents.rst

Updated `currents.rst` file with additional information from the `tutorial/shortcircuit.ipynb`, regarding the available short-circuit currents calculation methods. 
Merging this PR will close Issue #2054

Update currents.rst by providing additional information

---

.github/workflows/github_test_action.yml
.github/workflows/release.yml
doc/plotting/matplotlib/generic.rst
pandapower/plotting/generic_geodata.py
pandapower/test/plotting/test_generic_coordinates.py
setup.py
tutorials/plotting_basic.ipynb
tutorials/plotting_structural.ipynb

it has been renamed
cf. https://github.com/e2nIEE/pandapipes/issues/547

replace "python-igraph" by "igraph"

---

pandapower/build_branch.py

related to https://github.com/e2nIEE/pandapower/pull/2079
needed to fix failing tests in ieeopttool

complete rate_a

---

pandapower/auxiliary.py
pandapower/run.py
pandapower/test/converter/test_from_cim.py
pandapower/test/estimation/test_wls_estimation.py
pandapower/test/loadflow/test_facts.py
pandapower/test/loadflow/test_runpp.py
pandapower/test/toolbox/test_grid_modification.py
pandapower/timeseries/output_writer.py
tutorials/FACTS.ipynb

change the default for calculate_voltage_angles to True

---

CHANGELOG.rst
doc/converter/cgmes.rst

Change for loop documentation for several files to avoid confusion for new users.
move os.sep into loop to avoid problems with input folder

changes cim2pp documentation

---

.github/workflows/github_test_action.yml
CHANGELOG.rst
pandapower/contingency/contingency.py

after lightsim2grid version 0.8.0 release, the imports had to be modified in pandapower.contingency

fix lightsim2grid 0.8.0 imports

---

CHANGELOG.rst
pandapower/auxiliary.py

Regarding my issue #2204, I've moved some stuff around, now numba version get's only checked during import and not during every loadflow. And calc speed improved by around 3%.

[feature] improving speed #2204

---

pandapower/topology/graph_searches.py

closes #2241
updated the docstring of the function

fix for error in documentation of pp.topology.connected_components

---

.github/workflows/github_test_action.yml
CHANGELOG.rst
pandapower/test/loadflow/test_runpp_pgm.py

fix for python 3.8 since pgm then returns another error.

fix for python 3.8 since pgm then returns another error.

---

pandapower/plotting/collections.py
pandapower/plotting/plotting_toolbox.py
pandapower/plotting/simple_plot.py

fixed simple_plot not plotting lines that are missing geodata.

---

pandapower/plotting/collections.py

added switches argument to create_bus_bus_switch_collection

added support for partial switch collections to create_bus_bus_switch_collection 

---

CHANGELOG.rst
pandapower/plotting/collections.py
pandapower/plotting/patch_makers.py

Added create_ward_collection and create_xward_collection in collections.py. Fixed issue #2199. Added new patches for wards and xwards in patch_maker.py.

Modified collections.py and patch_makers.py to handle wards and xwards

---

tutorials/minimal_example.ipynb

as mentioned in #2382 , the results in the minimal example notebook where outdated, therefore updating them here

update results in minimal_example.ipynb

---

pandapower/convert_format.py

Readds the code to fix issue #2335 .

fixes #2335 again.

---

pandapower/test/toolbox/test_grid_modification.py

added test for issue #2321

---

CHANGELOG.rst
doc/powerflow/ac.rst
pandapower/auxiliary.py
pandapower/run.py

include compatibility issues to the documentation

improve lightsim2grid documentation

---

pandapower/converter/powerfactory/pp_import_functions.py

PR #2460 introduced some issues. Here are fixes for them.
fixed typo from removing ga wrapper in GetAttribute
fixed geodata being passed as string to create_bus function

Fixing issues from PR #2460

---

CHANGELOG.rst
pandapower/converter/cim/cim2pp/converter_classes/lines/dcLineSegmentsCim16.py
pandapower/test/converter/test_from_cim.py
pyproject.toml

cim2pp add description to dcline

fix cim2pp dcline description

---

pandapower/test/converter/test_from_ucte.py

Tests broke due to changes in the ucte importer. This fixes it.

fixed ucte tests.

---

pandapower/converter/powerfactory/pp_import_functions.py

Changes in the names of the functions in pf2pp converter lead to failing in the execution. I corrected the naming for the functions in the converter.

fix function names in pf2pp converter

---

CHANGELOG.rst
pandapower/converter/cim/cim2pp/converter_classes/lines/acLineSegmentsCim16.py
pandapower/converter/cim/cim_classes.py
pandapower/converter/cim/cim_tools.py

cim2pp: additional column "EquipmentContainer_id" in line table

cim2pp: additional column "EquipmentContainer_id" in line table

---

CHANGELOG.rst
pandapower/plotting/collections.py

like the title says, is only a small fix and only important if not all busses have geodata.

added a fix which hinders selection of a subsection of busses for plotting

---

pandapower/contingency/contingency.py

switched from bold warnings text to rtd warning box.
use of admonition for limitation

minor changes to documentation in contingency.py

---

CHANGELOG.rst
doc/elements/gen.rst
doc/elements/gen_par.csv
doc/elements/gen_q_capability_characteristic.csv
doc/elements/gen_q_capability_curve_table.csv
doc/elements/sgen.rst
doc/elements/sgen_par.csv
pandapower/build_gen.py
pandapower/control/__init__.py
pandapower/control/util/auxiliary.py
pandapower/control/util/diagnostic.py
pandapower/convert_format.py
pandapower/converter/cim/cim2pp/build_pp_net.py
pandapower/converter/cim/cim2pp/converter_classes/generators/synchronousMachinesCim16.py
pandapower/converter/powerfactory/pp_import_functions.py
pandapower/create.py
pandapower/test/api/test_auxiliary.py
pandapower/test/api/test_create.py
pandapower/test/converter/test_from_powerfactory.py
pandapower/test/loadflow/test_runpp.py
tutorials/q_reactive_power_capability.ipynb

* renamed q_capability_curve_characteristic to q_capability_characteristic to fix the 31 character length limit from Excel
* added documentation for q_capability_characteristic and q_capability_curve_table DataFrames in the pandapower net

renamed q_capability_curve_characteristic to q_capability_characteristic to fix the 31 character length limit from Excel

---

pandapower/control/controller/station_control.py

short fix for kwargs in station controller in reaction to recent changes to kwargs in run_control

Kwargs fix for station controller

---

.github/workflows/github_test_action.yml
CHANGELOG.rst
pandapower/sql_io.py

added support for using custom port in PostgreSQL database connection
added test for other port to the github actions test
closes #2644

PostgreSQL Port support

---

pandapower/converter/cim/cim2pp/converter_classes/transformers/powerTransformersCim16.py

changelog not needed, already in 
- [FIXED] cim2pp: minor speed increase through faster dict creation and removal of not needed .keys() call

fix missed dict constructors
